import numpy as np

# stadium attributes
# stadium
STADIUM_LENGTH = 105
STADIUM_WIDTH = 68
# center
CENTER_CIRCLE_RADIUS = 9.15
# penalty area
PENALTY_AREA_LENGTH = 16
PENALTY_AREA_WIDTH = 40
# goal area
GOAL_AREA_LENGTH = 6
GOAL_AREA_WIDTH = 20
# goal
GOAL_WIDTH = 12
# penalty spot
PENALTY_SPOT_DISTANCE = 11
PENALTY_SPOT_RADIUS = 0.25

# player attributes
PLAYER_RADIUS = 0.75
PLAYER_MAX_SPEED = 25
PLAYER_MAX_ROTATION = np.pi
PLAYER_MAX_KICKING_FORCE = 10

# ball attributes
BALL_RADIUS = 0.5

# simulation attributes
DT = 0.1
MAX_GAME_TIME = 1000
FPS = 60

# visual attributes
RENDER_SCALE = 12
PADDING = 10
WHITE = (255, 255, 255)
GREEN = (34, 139, 34)
ORANGE = (255, 165, 0)

# physics attributes
FRICTION_FACTOR = 0.9
ANGULAR_FRICTION_FACTOR = 0.9
AIR_RESISTANCE = 0.98